### ISSUE TITLE
Feature Request: Bot uses a different account than the streamer

### ISSUE THREAD

**Issue by jeovanny315** [GreenComfyTea/OBS-Stats-on-Stream#1]
I would like to use my separate chatbot account (315bot) for the readouts.

**Comment by GreenComfyTea** [comment]
It is already possible, you just need to generate OAuth password for your chatbot and use it instead of your own OAuth password. Log in with your chatbot in browser: [twitch.tv](https://twitch.tv) -> then go [here](https://twitchapps.com/tmi) and generate the OAuth password -> copy-paste into the script -> done!

**Comment by GreenComfyTea** [comment]
Oh sorry, It doesn't work as I thought it should. I will rewrite code to support this as soon as possible.

**Comment by GreenComfyTea** [comment]
Implemented in 7ccc9cd25cc9eea0a0d71b14ac4fbf574f02d84b. Closing it.
